export const Items = [
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1385_oshinko-maki.jpg",
    title: "ОШИНКО МАКИ",
    descripion: "Такуан, рис",
    gramm: "Вес:100 г",
    info: "КБЖУ:88/2/1/18",
    portion: "Порция: 6  шт.",
    price: "150.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1389_losos-avokado-.jpg",
    title: "ЛОСОСЬ-АВОКАДО",
    descripion: "Лосось, авокадо,  рис",
    gramm: "Вес:101 г",
    info: "КБЖУ:155/6/5/19",
    portion: "Порция: 6  шт.",
    price: "280.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1392_ogurets.jpg",
    title: "АВОКАДО-ОГУРЕЦ",
    descripion: "Авокадо, огурец, рис",
    gramm: "Вес:101г",
    info: "КБЖУ:115/3/3/19",
    portion: "Порция: 6  шт.",
    price: "150.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1393_krevetka.jpg",
    title: "ТУНЕЦ-АВОКАДО",
    descripion: "Тунец, авокадо,  рис",
    gramm: "Вес:101  г",
    info: "КБЖУ:129/6/4/18",
    portion: "Порция: 6  шт.",
    price: "220.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1394_maki-tunets.jpg",
    title: "МАКИ ТУНЕЦ",
    descripion: "Тунец еллоуфин, рис",
    gramm: "Вес:101 г",
    info: "КБЖУ:155/6/5/19",
    portion: "Порция: 6  шт.",
    price: "240.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1385_oshinko-maki.jpg",
    title: "ОШИНКО МАКИ",
    descripion: "Такуан, рис",
    gramm: "Вес:100 г",
    info: "КБЖУ:88/2/1/18",
    portion: "Порция: 6  шт.",
    price: "150.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1393_krevetka.jpg",
    title: "ТУНЕЦ-АВОКАДО",
    descripion: "Тунец, авокадо,  рис",
    gramm: "Вес:101  г",
    info: "КБЖУ:129/6/4/18",
    portion: "Порция: 6  шт.",
    price: "220.",
    cherta: "",
  },

];


