export const part1 = [
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1221_lux.jpg",
    title: "LUX",
    descripion:
      "Калифорния с крабом-стригуном и манго, Креветка в авокадо, Филадельфия, Дракон с креветкой",
    gramm: "Вес:900 г",
    portion: "Порция: 32 шт.",
    price: "2100.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1222_miks-4.jpg",
    title: "МИКС 4",
    descripion:
      "Калифорния с крабом-стригуном и манго, Дракон с креветкой, Филадельфия люкс, Манго-авокадо ",
    gramm: "Вес:902 г",
    portion: "Порция:32 шт.",
    price: "1950.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1223_miks-5.jpg",
    title: "МИКС 5",
    descripion: "Филадельфия, Креветка в авокадо, Эби темпура",
    gramm: "Вес:708 г",
    portion: "Порция:24 шт.",
    price: "1290.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1224_miks-7.jpg",
    title: "МИКС 7",
    descripion:
      "Запеченный тунец с сыром, Калифорния с креветками, Филадельфия, Манго-авокадо",
    gramm: "Вес:870 г",
    portion: "Порция:32 шт.",
    price: "1690.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1306_ugor-losos.jpg",
    title: "УГОРЬ-ЛОСОСЬ",
    descripion: "Филадельфия люкс, Дракон с креветкой, Креветка в авокадо   ",
    gramm: "Вес:732 г",
    info: "КБЖУ:1351/58/72/103",
    portion: "Порция:24 шт",
    price: "1650.",
    cherta: "",
  },
  {
    img: "https:takamura-eats.ru/userfls/shop/small/1230_miks-10.jpg",
    title: "МИКС 10",
    descripion: "Филадельфия, Креветка в авокадо, Острый лосось, Эби темпура  ",
    gramm: "Вес:909 г",
    portion: "Порция:32 шт",
    price: "1690.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1271_ostryy-nabor.jpg",
    title: "ОСТРЫЙ НАБОР",
    descripion: "Креветка-тунец, Креветка-лосось, Креветка-гребешок",
    gramm: "Вес:420 г",
    portion: "Порция:18 шт.",
    price: "1050.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1242_teplye-kholodnye.jpg",
    title: "ТЕПЛЫЕ-ХОЛОДНЫЕ",
    descripion:
      "Эби темпура, Запеченный угорь, Филадельфия люкс, Креветка FIT  ",
    gramm: "Вес:1000 г",
    portion: "Порция:32 шт.",
    price: "1910.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1305_klassika.jpg",
    title: "КЛАССИКА",
    descripion: "Лосось, Угорь, Тунец-авокадо, Креветка, Авокадо, Огурец   ",
    gramm: "Вес:605 г",
    info: "КБЖУ:831/34/28/116",
    portion: "Порция:36 шт.",
    price: "1100.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1269_miks-9.jpg",
    title: "МИКС 9",
    descripion: "Филадельфия, Креветка в авокадо, Острый лосось",
    gramm: "Вес:661 г ",
    portion: "Порция:24 шт",
    price: "1330.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1267_miks-8.jpg",
    title: "МИКС 8",
    descripion: "Филадельфия, Креветка Fit  ",
    gramm: "Вес:351 г ",
    portion: "Порция:12 шт",
    price: "690.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1270_tempura.jpg",
    title: "ТЕМПУРА",
    descripion: "Эби темпура, Унаги темпура, Филадельфия темпура ",
    gramm: "Вес:758 г",
    info: " КБЖУ:1588/53/54/126",
    portion: " Порция:24 шт.",
    price: "1280.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1268_miks.jpg",
    title: "МИКС",
    descripion: "Дракон с креветкой, Филадельфия лайт  ",
    gramm: "Вес:449 г ",
    info: "КБЖУ:895/39/47/61",
    portion: "Порция:16 шт.",
    price: "990.",
    cherta: "",
  },

  {
    img: "https://takamura-eats.ru/userfls/shop/small/1245_kaliforniya.jpg",
    title: "КАЛИФОРНИЯ",
    descripion: "Краб (имитация), авокадо, огурец, майонез, икра тобико",
    gramm: "Вес: 121 г",
    info: "КБЖУ: 152/6/8/21 ",
    portion: "Порция: 4 шт.",
    price: "190.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1244_kaliforniya.jpg",
    title: "КАЛИФОРНИЯ",
    descripion: "Краб (имитация), авокадо, огурец, майонез, икра тобико",
    gramm: "Вес:241 г",
    info: "КБЖУ:303/11/15/41 ",
    price: "370.",
    portion: "Порция: 8 шт.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1246_losos-pesto.jpg",
    title: "ЛОСОСЬ ПЕСТО",
    descripion: "Лосось, авокадо, огурец, соус пестоВес:108 г",
    gramm: "Вес: 241 г",
    info: "КБЖУ:142/7/7/15 ",
    portion: "Порция: 4 шт.",
    price: "290.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1247_losos-pesto.jpg",
    title: "ЛОСОСЬ ПЕСТО",
    descripion: "Лосось, авокадо, огурец, соус песто",
    gramm: "Вес: 216 г",
    info: "КБЖУ: 283/14/13/29 ",
    portion: "Порция: 8 шт.",

    price: "570.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1249_filadelfiya-fit.jpg",
    title: "ФИЛАДЕЛЬФИЯ FIT",
    descripion: "Лосось, сливочный сыр, авокадо, икра тобико ",
    gramm: "Вес: 96 г ",
    info: "КБЖУ: 138/4/6/17 ",
    portion: "Порция: 4 шт.",
    price: "270.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1248_filadelfiya-fit.jpg",
    title: "ФИЛАДЕЛЬФИЯ FIT",
    descripion: "Лосось, сливочный сыр, авокадо, икра тобико ",
    gramm: "Вес: 191 г",
    info: "КБЖУ: 276/8/13/34 ",
    portion: "Порция: 8 шт.",
    price: "530.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1251_slivochnaya-krevetka.jpg",
    title: "СЛИВОЧНАЯ КРЕВЕТКА",
    descripion:
      "Угорь, тигровые креветки, сливочный сыр Cremette, огурецВес:105 г КБЖУ:154/7/7/17 Порция:4 шт.",
    gramm: "Вес: 191 г",
    info: "КБЖУ: 276/8/13/34 ",
    portion: "Порция: 4 шт.",
    price: "239.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1250_slivochnaya-krevetka.jpg",
    title: "СЛИВОЧНАЯ КРЕВЕТКА",
    descripion: "Лосось, авокадо, огурец, соус песто ",
    gramm: "Вес: 216 г",
    info: "КБЖУ: 283/14/13/29 ",
    portion: "Порция: 8 шт.",

    price: "450.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1253_filadelfiya-layt.jpg",
    title: "ФИЛАДЕЛЬФИЯ ЛАЙТ",
    descripion: "Лосось, сливочный сыр ",
    gramm: "Вес: 85 г",
    info: "КБЖУ: 140/8/7/13 ",
    portion: "Порция: 4 шт.",

    price: "230.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1252_filadelfiya-layt.jpg",
    title: "ФИЛАДЕЛЬФИЯ ЛАЙТ",
    descripion: "Лосось, сливочный сыр",
    gramm: "Вес: 170 г ",
    info: "КБЖУ: 280/15/13/26 ",
    portion: "Порция: 8 шт.",

    price: "450.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1272_nyu-york.jpg",
    title: "НЬЮ-ЙОРК",
    descripion:
      "Авокадо, тигровые креветки, лососьВес:98 г КБЖУ:127/7/5/14 Порция:4 шт..",
    gramm: "Вес: 170 г ",
    info: "КБЖУ: 280/15/13/26 ",
    portion: "Порция: 4 шт.",

    price: "325.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1274_nyu-york.jpg",
    title: "НЬЮ-ЙОРК",
    descripion: "Авокадо, тигровые креветки, лосось ",
    gramm: "Вес: 196 г ",
    info: " КБЖУ: 254/15/9/29 ",
    portion: "Порция: 8 шт.",

    price: "640.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1259_ostryy-losos.jpg",
    title: "ОСТРЫЙ ЛОСОСЬ",
    descripion: "Лосось, сливочный сыр, огурец, соус шрирача",
    gramm: "Вес:101 г  ",
    info: "КБЖУ: 180/7/9/14  ",
    portion: "Порция: 4 шт.",

    price: "255.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1258_ostryy-losos.jpg",
    title: "ОСТРЫЙ ЛОСОСЬ",
    descripion: "Лосось, сливочный сыр, огурец, соус шрирача",
    gramm: "Вес:201 г",
    info: "КБЖУ: 360/14/18/29 ",
    portion: "Порция: 8 шт.",

    price: "500.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1275_bonito.jpg",
    title: "БОНИТО",
    descripion: "Копченый лосось, сливочный сыр, такуан, стружка тунца ",
    gramm: "Вес: 109 г ",
    info: "КБЖУ: 172/9/9/16 ",
    portion: "Порция: 4 шт.",

    price: "255.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1276_bonito-.jpg",
    title: "БОНИТО",
    descripion: "Копченый лосось, сливочный сыр, такуан, стружка тунца ",
    gramm: "Вес:218 г",
    info: "КБЖУ:344/17/19/32 ",
    portion: "Порция: 8 шт.",

    price: "480.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1283_slivochnyy-ugor.jpg",
    title: "СЛИВОЧНЫЙ УГОРЬ",
    descripion: "Угорь, копченый лосось, сливочный сыр, огурец ",
    gramm: "Вес: 101 г ",
    info: "КБЖУ: 155/6/9/17 ",
    portion: "Порция: 4 шт.",

    price: "230.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1284_slivochnyy-ugor.jpg",
    title: "СЛИВОЧНЫЙ УГОРЬ",
    descripion: "Угорь, копченый лосось, сливочный сыр, огурец ",
    gramm: "Вес:203 г",
    info: "КБЖУ:310/12/18/34 ",
    portion: "Порция: 8 шт.",

    price: "450.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1285_kaliforniya-s-krevetkoy.jpg",
    title: "КАЛИФОРНИЯ С КРЕВЕТКОЙ",
    descripion: "Тигровые креветки, авокадо, огурец, икра тобико ",
    gramm: "Вес: 108 г",
    info: "КБЖУ: 117/9/2/15 ",
    portion: "Порция: 4 шт.",

    price: "260.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1286_kaliforniya-s-krevetkoy.jpg",
    title: "КАЛИФОРНИЯ С КРЕВЕТКОЙ",
    descripion: "Тигровые креветки, авокадо, огурец, икра тобико ",
    gramm: "Вес: 216 г",
    info: "КБЖУ: 235/18/5/30 ",
    portion: "Порция: 4 шт.",

    price: "510.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1302_roll-v-avokado.jpg",
    title: "РОЛЛ В АВОКАДО",
    descripion: "Лосось, сливочный сыр Cremette, авокадо, огурец",
    gramm: "Вес: 118",
    info: "КБЖУ: 205/6/11/17 ",
    portion: "Порция: 4 шт.",

    price: "250.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1303_roll-v-avokado.jpg",
    title: "РОЛЛ В АВОКАДО",
    descripion: "Лосось, сливочный сыр Cremette, авокадо, огурец  ",
    gramm: "Вес:236 г",
    info: "КБЖУ:409/13/22/34 ",
    portion: "Порция: 8 шт.",

    price: "490.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1287_vulkan.jpg",
    title: "ВУЛКАН",
    descripion: "Угорь, лосось, сливочный сыр Cremette, соус унаги ",
    gramm: "Вес: 103 г ",
    info: "КБЖУ: 204/7/12/18 ",
    portion: "Порция: 4 шт.",

    price: "270.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1288_vulkan.jpg",
    title: "ВУЛКАН",
    descripion: "Угорь, лосось, сливочный сыр Cremette, соус унаги",
    gramm: "Вес:206 г",
    info: "КБЖУ: 407/15/24/36 ",
    portion: "Порция: 8 шт.",

    price: "530.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1278_-krevetka-v-avokado.jpg",
    title: "КРЕВЕТКА В АВОКАДО",
    descripion: "Креветка темпура, авокадо авокадо, огурец",
    gramm: "Вес: 100 г",
    info: "КБЖУ: 115/4/5/15 ",
    portion: "Порция: 4 шт.",

    price: "225.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1303_roll-v-avokado.jpg",
    title: "КРЕВЕТКА В АВОКАДО",
    descripion: "Креветка темпура, авокадо авокадо, огурец",
    gramm: "Вес: 236 г",
    info: "КБЖУ: 115/4/5/15 ",
    portion: "Порция: 8 шт.",

    price: "440.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1291_opalennyy-grebeshok.jpg",
    title: "ОПАЛЕННЫЙ ГРЕБЕШОК",
    descripion: "Морской гребешок, авокадо, сливочный сыр, икра тобико",
    gramm: "Вес: 98 г",
    info: "КБЖУ:139/6/6/15 ",
    portion: "Порция: 4 шт.",

    price: "300.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1292_opalennyy-grebeshok.jpg",
    title: "ОПАЛЕННЫЙ ГРЕБЕШОК",
    descripion: "Морской гребешок, авокадо, сливочный сыр, икра тобико",
    gramm: "Вес: 196 г",
    info: "КБЖУ: 279/12/13/29 ",
    portion: "Порция: 8 шт.",

    price: "590.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1293_ikura-roll.jpg",
    title: "ИКУРА РОЛЛ",
    descripion: "Икра лососевых рыб, лосось, сливочный сыр",
    gramm: "Вес: 93 г",
    info: "КБЖУ:279/12/13/29 ",
    portion: "Порция: 4 шт.",

    price: "295.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1294_ikura-roll.jpg",
    title: "ИКУРА РОЛЛ",
    descripion: "Икра лососевых рыб, лосось, сливочный сыр",
    gramm: "Вес: 186 г",
    info: "КБЖУ:363/16/19/27 ",
    portion: "Порция: 8 шт.",

    price: "580.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1289_veg-roll.jpg",
    title: "VEG РОЛЛ",
    descripion: "Авокадо, огурец",
    gramm: "Вес: 96 г",
    info: "КБЖУ:111/2/5/16 ",
    portion: "Порция: 4 шт.",

    price: "130.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1289_veg-roll.jpg",
    title: "VEG РОЛЛ",
    descripion: "Авокадо, огурец",
    gramm: "Вес: 191 г",
    info: "КБЖУ:221/4/10/31 ",
    portion: "Порция: 8 шт.",

    price: "250.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1295_drakon-fit.jpg",
    title: "ДРАКОН FIT",
    descripion: "Угорь, тигровые креветки, мягкое авокадо, соус унаги,  кунжут",
    gramm: "Вес: 101 г",
    info: "КБЖУ:155/8/9/18 ",
    portion: "Порция: 4 шт.",

    price: "295.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1295_drakon-fit.jpg",
    title: "ДРАКОН FIT",
    descripion: "Угорь, тигровые креветки, мягкое авокадо, соус унаги,  кунжут",
    gramm: "Вес: 201  г",
    info: "КБЖУ:155/8/9/18",
    portion: "Порция: 8 шт.",

    price: "580.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1297_kaliforniya-s-tuntsom.jpg",
    title: "КАЛИФОРНИЯ С ТУНЦОМ",
    descripion:
      "Тунец еллоуфин, авокадо, огурец, икра летучей рыбы тобико, рис",
    gramm: "Вес: 201  г",
    info: "КБЖУ:155/8/9/18 ",
    portion: "Порция: 4 шт.",
    price: "260.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1298_kaliforniya-s-tuntsom.jpg",
    title: "КАЛИФОРНИЯ С ТУНЦОМ",
    descripion:
      "Тунец еллоуфин, авокадо, огурец, икра летучей рыбы тобико, рис",
    gramm: "Вес: 196 г",
    info: "КБЖУ:213/15/5/29",
    portion: "Порция: 8 шт.",
    price: "510.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1300_tunets-losos-avokado.jpg",
    title: "ТУНЕЦ, ЛОСОСЬ, АВОКАДО",
    descripion:
      "Тунец еллоуфин, авокадо, огурец, икра летучей рыбы тобико, рис",
    gramm: "Вес: 100 г",
    info: "КБЖУ: 122/8/4/15",
    portion: "Порция: 4 шт.",
    price: "295.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1300_tunets-losos-avokado.jpg",
    title: "ТУНЕЦ, ЛОСОСЬ, АВОКАДО",
    descripion:
      "Тунец еллоуфин, авокадо, огурец, икра летучей рыбы тобико, рис",
    gramm: "Вес: 201  г",
    info: "КБЖУ: 244/15/8/30",
    portion: "Порция: 8 шт.",
    price: "580.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1205_drakon-s-krevetkoy.jpg",
    title: "ДРАКОН С КРЕВЕТКОЙ",
    descripion: "Угорь, тигровые креветки, такуан, сливочный сыр",
    gramm: "Вес: 110 г",
    portion: "Порция: 4 шт.",
    price: "280.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1205_drakon-s-krevetkoy.jpg",
    title: "ДРАКОН С КРЕВЕТКОЙ",
    descripion: "Угорь, тигровые креветки, такуан, сливочный сыр",
    gramm: "Вес: 220 г",
    portion: "Порция: 8 шт.",
    price: "550.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1157_filadelfiya-lyuks.jpg",
    title: "ФИЛАДЕЛЬФИЯ ЛЮКС",
    descripion: "Лосось, сливочный сыр",
    gramm: "Вес: 281 г",
    portion: "Порция: 8 шт.",
    info: "КБЖУ: 244/15/8/30",
    price: "680.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1157_filadelfiya-lyuks.jpg",
    title: "ФИЛАДЕЛЬФИЯ ЛЮКС",
    descripion: "Лосось, сливочный сыр",
    gramm: "Вес: 141 г",
    portion: "Порция: 4 шт.",
    info: "КБЖУ: 145/15/7/30",
    price: "345.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1207_kaliforniya-s-krabom-strigu.jpg",
    title: "КАЛИФОРНИЯ С КАМЧАТСКИМ КРАБОМ ",
    descripion: "Камчатский краб, авокадо, огурец, икра тобико, майонез",
    gramm: "Вес: 195 г",
    portion: "Порция: 8 шт.",
    price: "620.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1207_kaliforniya-s-krabom-strigu.jpg",
    title: "КАЛИФОРНИЯ С КАМЧАТСКИМ КРАБОМ ",
    descripion: "Камчатский краб, авокадо, огурец, икра тобико, майонез",
    gramm: "Вес: 98 г",
    portion: "Порция: 4 шт.",
    price: "315.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1225_kaliforniya-s-krabom-i-mango.jpg",
    title: "КАЛИФОРНИЯ С КАМЧАТСКИМ КРАБОМ И МАНГО",
    descripion: "Камчатский краб, манго, авокадо, тобико, майонез",
    gramm: "Вес: 190 г",
    portion: "Порция: 8 шт.",
    price: "600.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1225_kaliforniya-s-krabom-i-mango.jpg",
    title: "КАЛИФОРНИЯ С КАМЧАТСКИМ КРАБОМ И МАНГО",
    descripion: "Камчатский краб, манго, авокадо, тобико, майонез",
    gramm: "Вес: 95 г",
    portion: "Порция: 4 шт.",
    price: "305.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1227_mango-avokado.jpg",
    title: "МАНГО-АВОКАДО",
    descripion: "Манго, сливочный сыр, авокадо",
    gramm: "Вес: 95 г",
    portion: "Порция: 8 шт.",
    price: "350 .",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1227_mango-avokado.jpg",
    title: "МАНГО-АВОКАДО",
    descripion: "Манго, сливочный сыр, авокадо",
    gramm: "Вес: 102 г",
    portion: "Порция: 4 шт.",
    price: "180.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1075_tayga.jpg",
    title: "ТАЙГА ",
    descripion: "Тунец, сливочный сыр, авокадо, опаленный лосось",
    gramm: "Вес: 210 г",
    info: "КБЖУ: 318/17/15/28",
    portion: "Порция: 8 шт.",
    price: "580 .",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1075_tayga.jpg",
    title: "ТАЙГА ",
    descripion: "Тунец, сливочный сыр, авокадо, опаленный лосось",
    gramm: "Вес: 105 г",
    info: "КБЖУ: 159/9/8/14",
    portion: "Порция: 4 шт.",
    price: "295.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1071_krevetka-kayso.jpg",
    title: "КРЕВЕТКА КАЙСО",
    descripion: "Креветка темпура, сливочный сыр, лосось, кайсо",
    gramm: "Вес: 220 г",
    info: "КБЖУ: 298/18/12/29",
    portion: "Порция: 8 шт.",
    price: "580.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1071_krevetka-kayso.jpg",
    title: "КРЕВЕТКА КАЙСО",
    descripion: "Креветка темпура, сливочный сыр, лосось, кайсо",
    gramm: "Вес: 110 г",
    info: "КБЖУ: 149/9/6/14",
    portion: "Порция: 4 шт.",
    price: "295.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1194_krevetka-fit.jpg",
    title: "КРЕВЕТКА КАЙСО",
    descripion: "Тигровые креветки, тунец, лосось, авокадо,  кунжут",
    gramm: "Вес: 181 г",
    info: "КБЖУ: 270/13/11/29",
    portion: "Порция: 8 шт.",
    price: "460.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1194_krevetka-fit.jpg",
    title: "КРЕВЕТКА КАЙСО",
    descripion: "Тигровые креветки, тунец, лосось, авокадо,  кунжут",
    gramm: "Вес: 91 г",
    info: "КБЖУ: 135/7/6/15",
    portion: "Порция: 4 шт.",
    price: "235.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1149_maguro-fit.jpg",
    title: "МАГУРО FIT",
    descripion: "Тунец еллоуфин, авокадо",
    gramm: "Вес: 230 г",
    info: "КБЖУ: 297/22/11/28",
    portion: "Порция: 8 шт.",
    price: "570.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1149_maguro-fit.jpg",
    title: "МАГУРО FIT",
    descripion: "Тунец еллоуфин, авокадо",
    gramm: "Вес: 115 г",
    info: "КБЖУ: 148/11/5/14",
    portion: "Порция: 4 шт.",
    price: "290.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1085_kaliforniya-losos.jpg",
    title: "КАЛИФОРНИЯ С ЛОСОСЕМ",
    descripion: "Лосось, авокадо, огурец, икра тобико",
    gramm: "Вес: 196 г",
    info: "КБЖУ: 222/14/6/29",
    portion: "Порция: 8 шт.",
    price: "590.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1085_kaliforniya-losos.jpg",
    title: "КАЛИФОРНИЯ С ЛОСОСЕМ",
    descripion: "Лосось, авокадо, огурец, икра тобико",
    gramm: "Вес: 98 г",
    info: "КБЖУ: 111/7/3/14",
    portion: "Порция: 4 шт.",
    price: "300.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1087_kanada.jpg",
    title: "КАНАДА",
    descripion: "Угорь, лосось, огурец, сливочный сыр, соус унаги,  кунжут",
    gramm: "Вес: 254 г",
    info: "КБЖУ: 466/18/30/42",
    portion: "Порция: 8 шт.",
    price: "600.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1087_kanada.jpg",
    title: "КАНАДА",
    descripion: "Угорь, лосось, огурец, сливочный сыр, соус унаги,  кунжут",
    gramm: "Вес: 127 г",
    info: "КБЖУ: 233/9/15/21",
    portion: "Порция: 4 шт.",
    price: "305.",
    cherta: "",
  },

];
