export const part2 = [
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1316_zapechennyy-ugor-s-syrom.jpg",
    title: "ЗАПЕЧЕННЫЙ УГОРЬ С СЫРОМ",
    descripion: "Угорь, сливочный сыр, сыр гауда, соус шрирача, кунжут",
    gramm: "Вес: 106  г",
    info: "КБЖУ: 216/8/16/19",
    portion: "Порция: 4 шт.",
    price: "245.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1411_zapechennyy-ugor-s-syrom.jpg",
    title: "ЗАПЕЧЕННЫЙ УГОРЬ С СЫРОМ",
    descripion: "Угорь, сливочный сыр, сыр гауда, соус шрирача, кунжут",
    gramm: "Вес: 211 г",
    info: "КБЖУ: 216/8/16/19",
    portion: "Порция:8 шт.",
    price: "480 .",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1412_zapechennyy-tunets-s-syrom.jpg",
    title: "ЗАПЕЧЕННЫЙ ТУНЕЦ С СЫРОМ",
    descripion:
      "Тунец еллоуфин, сливочный сыр, сыр гауда, соус шрирача, кунжут",
    gramm: "Вес: 106 г",
    info: "КБЖУ: 183/10/9/15",
    portion: "Порция: 4 шт.",
    price: "230 .",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1413_zapechennyy-tunets-s-syrom.jpg",
    title: "ЗАПЕЧЕННЫЙ ТУНЕЦ С СЫРОМ",
    descripion:
      "Тунец еллоуфин, сливочный сыр, сыр гауда, соус шрирача, кунжут",
    gramm: "Вес: 211 г",
    info: "КБЖУ: 366/19/19/30",
    portion: "Порция: 8 шт.",
    price: "450.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1413_zapechennyy-tunets-s-syrom.jpg",
    title: "ЗАПЕЧЕННЫЙ ЛОСОСЬ С СЫРОМ",
    descripion: "Лосось, сливочный сыр, сыр гауда, соус шрирача, кунжут",
    gramm: "Вес: 106  г",
    info: "КБЖУ: 216/8/16/19",
    portion: "Порция: 4 шт.",
    price: "280.",
    cherta: "",
  },
  {
    img: "https://takamura-eats.ru/userfls/shop/small/1411_zapechennyy-ugor-s-syrom.jpg",
    title: "ЗАПЕЧЕННЫЙ УГОРЬ С СЫРОМ",
    descripion: "Угорь, сливочный сыр, сыр гауда, соус шрирача, кунжут",
    gramm: "Вес: 211 г",
    info: "КБЖУ: 216/8/16/19",
    portion: "Порция:8 шт.",
    price: "480 .",
    cherta: "",
  },
];
